name: Deploy CDK Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy:
    name: Deploy CDK Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm ci
      
    - name: Deploy CDK Application
      run: |
        npm run build
        npx cdk deploy --app-complete --require-approval never
